apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: dp-arena-trakt
  namespace: teamdagpenger
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dp-quiz-mediator
  minReplicas: {{replicas.min}}
  maxReplicas: {{replicas.max}}
  metrics:
    - type: External
      external:
        metric:
          name: kafka_consumergroup_group_lag
          selector:
            matchLabels:
              group: {{kafka.consumer_group_id}}
        target:
          type: AverageValue
          averageValue: 500