apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: {{ app }}
  namespace: teamdagpenger
  labels:
    team: teamdagpenger
    app: {{ app }}
spec:
  image: {{image}}
  port: 8080
  strategy:
    type: Recreate
  liveness:
    path: /isalive
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /isready
    timeout: 1
  prometheus:
    enabled: false
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 300m
      memory: 256Mi
  secureLogs:
    enabled: true
  env:
    - name: PORT
      value: "8080"
  filesFrom:
    - secret: serviceuser-srvdp-quiz-mediator
      mountPath: "/var/run/secrets/nais.io/service_user"
  kafka:
    pool: {{ kafka_pool }}
  gcp:
    sqlInstances:
      - name: dp-quiz-mediator
        type: POSTGRES_12
        tier:  {{ db_tier }}
        diskType: SSD
        highAvailability: false
        diskSize: {{ db_size }}
        diskAutoresize: true
        pointInTimeRecovery: true
        retainedBackups: {{ point_in_time_recovery_days }}
        autoBackupTime: "03:00"
        maintenance:
          day: 1
          hour: 3
        databases:
          - name: quiz
            envVarPrefix: DB
        cascadingDelete: false
