apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: {{app}}
  namespace: {{namespace}}
  labels:
    team: {{team}}
spec:
  image: {{ image }}
  port: 8080
  strategy:
    type: Recreate
  ingresses:
  {{#each ingresses as |url|}}
    - https://{{url}}.nais.preprod.local
    - https://{{url}}.dev-fss.nais.io
  {{/each}}
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 70
  liveness:
    path: /isalive
  readiness:
    path: /isready
  prometheus:
    enabled: true
    path: /metrics
  resources:
    limits:
      cpu: 600m
      memory: 1024Mi
    requests:
      cpu: 300m
      memory: 384Mi
  secureLogs:
    enabled: true
  vault:
    enabled: true
    paths:
      - kvPath: "serviceuser/data/dev/{{service_user}}"
        mountPath: "/var/run/secrets/nais.io/service_user"
  env:
    - name: KAFKA_BOOTSTRAP_SERVERS
      value: b27apvl00045.preprod.local:8443,b27apvl00046.preprod.local:8443,b27apvl00047.preprod.local:8443
    - name: KAFKA_RAPID_TOPIC
      value: foo
    - name: KAFKA_CONSUMER_GROUP_ID
      value: dp-quiz-v1
