ALTER TABLE faktum_verdi ADD COLUMN IF NOT EXISTS desimaltall DOUBLE PRECISION NULL;
ALTER TABLE gammel_faktum_verdi ADD COLUMN IF NOT EXISTS desimaltall DOUBLE PRECISION;
ALTER TABLE faktum ALTER COLUMN regel TYPE VARCHAR(32);